### ISSUE TITLE
Folders not in Chronological Order.

### ISSUE THREAD

**Issue by DeroPlayz** [LilyLavender/smashline-tutorial#1]
This is essentially just a nitpick, but if Episodes 1-9 were titled 01, 02, 03, etc., they would display in chronological order.

**Comment by LilyLavender** [comment]
Thanks, that's fixed now. Saw you also mentioned the fact that episode 6 is missing, this was a conscious decision, as I didn't actually write any code during it. You could make the argument that it would help someone to be able to use code that they know for a fact works for troubleshooting purposes, but unless someone else actually _wants_ 6 there, I'll keep it omitted.
